/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modele.Commercial;
import modele.ListeFacture;
import modele.RegistreCommercial;
import utils.CommercialDoublonException;

/**
 *
 * @author houas
 */
public class FenFlouAliments extends javax.swing.JFrame {



    private RegistreCommercial listing;
    

    /**
     * Creates new form FenFlouAliments
     */
    public FenFlouAliments() {
        initComponents();
    }

    public FenFlouAliments(RegistreCommercial listing) {
        this();
        this.listing = listing;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnEspaceCommerciaux = new javax.swing.JButton();
        panAjoutCommercial = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        txtPrenom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        CK_Super = new javax.swing.JCheckBox();
        CK_Senior = new javax.swing.JCheckBox();
        CK_Junior = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListeCommerciaux = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        btnModifierCommercial = new javax.swing.JButton();
        btnTelechargerFile = new javax.swing.JButton();
        btnAjouterCommercial = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnDeleteCommercial = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion des frais des commerciaux");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(716, 760));
        setResizable(false);

        body.setBackground(new java.awt.Color(0, 0, 102));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        jLabel1.setText("FlouAliments");

        btnExit.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/spower1.svg.png"))); // NOI18N
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnEspaceCommerciaux.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user-apply.svg.png"))); // NOI18N
        btnEspaceCommerciaux.setText("EspaceCommerciaux");
        btnEspaceCommerciaux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEspaceCommerciauxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEspaceCommerciaux)
                .addGap(16, 16, 16)
                .addComponent(btnExit)
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(btnExit))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(btnEspaceCommerciaux)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        panAjoutCommercial.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user-add.svg.png"))); // NOI18N
        jLabel7.setText("Ajouter Commerciaux");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/id.png"))); // NOI18N
        jLabel2.setText(" ID_Commercial :");
        jLabel2.setMaximumSize(new java.awt.Dimension(113, 25));
        jLabel2.setMinimumSize(new java.awt.Dimension(113, 25));
        jLabel2.setPreferredSize(new java.awt.Dimension(113, 25));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/identity.png"))); // NOI18N
        jLabel3.setText(" Nom :");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/identity.png"))); // NOI18N
        jLabel4.setText(" Prenom :");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/courriel.png"))); // NOI18N
        jLabel5.setText(" E-mail :");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/phone.png"))); // NOI18N
        jLabel6.setText(" N° Telephone :");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Information Commercial");

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        CK_Super.setBackground(new java.awt.Color(255, 255, 255));
        CK_Super.setText("Super");
        CK_Super.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CK_SuperActionPerformed(evt);
            }
        });

        CK_Senior.setBackground(new java.awt.Color(255, 255, 255));
        CK_Senior.setText("Senior");
        CK_Senior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CK_SeniorActionPerformed(evt);
            }
        });

        CK_Junior.setBackground(new java.awt.Color(255, 255, 255));
        CK_Junior.setText("Junior");
        CK_Junior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CK_JuniorActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText(" Categorie :");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(CK_Super)
                .addGap(18, 18, 18)
                .addComponent(CK_Senior)
                .addGap(12, 12, 12)
                .addComponent(CK_Junior)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CK_Super)
                    .addComponent(CK_Senior)
                    .addComponent(CK_Junior))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtPrenom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNom)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtId)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/imgFA.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(438, 438, 438))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel9)
        );

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 102));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/unordered-list.svg.png"))); // NOI18N
        jLabel10.setText("Listes Commerciaux");

        ListeCommerciaux.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nom", "Prenom", "E-mail", "Tel", "categorie"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        ListeCommerciaux.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListeCommerciauxMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ListeCommerciaux);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(32, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        btnModifierCommercial.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnModifierCommercial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/update.png"))); // NOI18N
        btnModifierCommercial.setText("Edit");
        btnModifierCommercial.setMaximumSize(new java.awt.Dimension(72, 31));
        btnModifierCommercial.setMinimumSize(new java.awt.Dimension(72, 31));
        btnModifierCommercial.setPreferredSize(new java.awt.Dimension(72, 31));
        btnModifierCommercial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierCommercialActionPerformed(evt);
            }
        });

        btnTelechargerFile.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnTelechargerFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user-download.svg.png"))); // NOI18N
        btnTelechargerFile.setText("download");
        btnTelechargerFile.setMaximumSize(new java.awt.Dimension(83, 31));
        btnTelechargerFile.setMinimumSize(new java.awt.Dimension(83, 31));
        btnTelechargerFile.setPreferredSize(new java.awt.Dimension(83, 31));
        btnTelechargerFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelechargerFileActionPerformed(evt);
            }
        });

        btnAjouterCommercial.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnAjouterCommercial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user-add.svg.png"))); // NOI18N
        btnAjouterCommercial.setText("Add");
        btnAjouterCommercial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterCommercialActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clear.png"))); // NOI18N
        btnClear.setText("Clear");
        btnClear.setMaximumSize(new java.awt.Dimension(72, 31));
        btnClear.setMinimumSize(new java.awt.Dimension(72, 31));
        btnClear.setPreferredSize(new java.awt.Dimension(72, 31));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnDeleteCommercial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user-delete.svg.png"))); // NOI18N
        btnDeleteCommercial.setText("Delete");
        btnDeleteCommercial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCommercialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAjouterCommercial, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnModifierCommercial, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDeleteCommercial, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(btnTelechargerFile, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAjouterCommercial)
                    .addComponent(btnModifierCommercial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteCommercial, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTelechargerFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panAjoutCommercialLayout = new javax.swing.GroupLayout(panAjoutCommercial);
        panAjoutCommercial.setLayout(panAjoutCommercialLayout);
        panAjoutCommercialLayout.setHorizontalGroup(
            panAjoutCommercialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAjoutCommercialLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panAjoutCommercialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        panAjoutCommercialLayout.setVerticalGroup(
            panAjoutCommercialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panAjoutCommercialLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(243, 243, 243))
        );

        javax.swing.GroupLayout bodyLayout = new javax.swing.GroupLayout(body);
        body.setLayout(bodyLayout);
        bodyLayout.setHorizontalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panAjoutCommercial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bodyLayout.setVerticalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panAjoutCommercial, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(473, 473, 473))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("@ FlouAliments");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(body, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAjouterCommercialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterCommercialActionPerformed
        Boolean status = validerData();

        if (status) {//valider que les champs sont saisie
            String categories = "junior";
            if (CK_Super.isSelected()) {
                categories = "super ";
            }
            if (CK_Senior.isSelected()) {
                categories = "senior ";
            }
            if (CK_Junior.isSelected()) {
                categories = "junior ";
            }
            Commercial com = new Commercial(Integer.parseInt(txtId.getText()), txtNom.getText(), txtPrenom.getText(), txtEmail.getText(), txtTel.getText(), categories);
            try {
                listing.ajouterCommercial(com);
            } catch (CommercialDoublonException e) {
                JOptionPane.showMessageDialog(null, e.getCom().toString(), "Erreur Ajout", JOptionPane.ERROR_MESSAGE);
            }
        }

        listingCommerciaux();
        
        
        
    }//GEN-LAST:event_btnAjouterCommercialActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed
     private void listingCommerciaux() {
        DefaultTableModel model = (DefaultTableModel)ListeCommerciaux.getModel();
        
        //Afficher table
        
        //Vider JTable table
        model.setRowCount(0);
        //Alimenter le JTable
        
        for (Commercial com : listing.getRegistre()){
            model.addRow(new Object[]{com.getId_commercial(), com.getNom(), com.getPrenom(), com.getEmail(),com.getTel(),com.getCategories()});
        }
    }

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
    viderChamps();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnDeleteCommercialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCommercialActionPerformed
      DefaultTableModel model = (DefaultTableModel)ListeCommerciaux.getModel();
      int i = ListeCommerciaux.getSelectedRow();
      if (i>=0){
      model.removeRow(i);
      JOptionPane.showMessageDialog(null, "Delete successfully");
      }else if(ListeCommerciaux.getRowCount() == 0){
            JOptionPane.showMessageDialog(this, "Table is Empty");
      }
      else{
       JOptionPane.showMessageDialog(null, "please Select a row");

      }
      
    }//GEN-LAST:event_btnDeleteCommercialActionPerformed

    private void btnModifierCommercialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierCommercialActionPerformed
    DefaultTableModel model = (DefaultTableModel)ListeCommerciaux.getModel();
    if(ListeCommerciaux.getSelectedRowCount()== 1){
        int id = Integer.parseInt(txtId.getText());
        String Nom = txtNom.getText();
        String Prenom = txtPrenom.getText();
        String Email = txtEmail.getText();
        String Tel = txtTel.getText();
        
        
        model.setValueAt(id, ListeCommerciaux.getSelectedRow() , 0);
        model.setValueAt(Nom, ListeCommerciaux.getSelectedRow() , 1);
        model.setValueAt(Prenom, ListeCommerciaux.getSelectedRow() , 2);
        model.setValueAt(Email, ListeCommerciaux.getSelectedRow() , 3);
        model.setValueAt(Tel, ListeCommerciaux.getSelectedRow() , 4);
      
        // confirmation Update
        JOptionPane.showMessageDialog(this, "Update Successfully");
        viderChamps();
        
    }else{
        if(ListeCommerciaux.getRowCount() == 0){
            JOptionPane.showMessageDialog(this, "Table is Empty");

        }else{
            JOptionPane.showMessageDialog(this, "Please select Single Row for Update");

        }
        
    }
    
    }//GEN-LAST:event_btnModifierCommercialActionPerformed

    private void ListeCommerciauxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListeCommerciauxMouseClicked
    DefaultTableModel model = (DefaultTableModel)ListeCommerciaux.getModel();
    //Set data to textField when row is selected
    
    String id = model.getValueAt(ListeCommerciaux.getSelectedRow(), 0).toString();
    String Nom = model.getValueAt(ListeCommerciaux.getSelectedRow(), 1).toString();
    String Prenon = model.getValueAt(ListeCommerciaux.getSelectedRow(), 2).toString();
    String Email = model.getValueAt(ListeCommerciaux.getSelectedRow(), 3).toString();
    String Tel = model.getValueAt(ListeCommerciaux.getSelectedRow(), 4).toString();
    
    
    //Set to textField
    txtId.setText(id);
    txtNom.setText(Nom);
    txtPrenom.setText(Prenon);
    txtEmail.setText(Email);
    txtTel.setText(Tel);
    
    }//GEN-LAST:event_ListeCommerciauxMouseClicked

    private void btnTelechargerFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelechargerFileActionPerformed
       
        utils.ManipulationFichier.ecritureIOCommerciaux(listing);
         JOptionPane.showMessageDialog(null, "Chargement reussi", "Chargement",
                JOptionPane.INFORMATION_MESSAGE);
    
    }//GEN-LAST:event_btnTelechargerFileActionPerformed

    private void btnEspaceCommerciauxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEspaceCommerciauxActionPerformed
        ListeFacture depens = new ListeFacture();
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenEspaceCommerciaux(depens).setVisible(true);
                FenFlouAliments fl = new FenFlouAliments();
                fl.dispose();
               
                
            }
            
        });
           
    }//GEN-LAST:event_btnEspaceCommerciauxActionPerformed

    private void CK_SuperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CK_SuperActionPerformed
        if(CK_Super.isSelected()){
            CK_Senior.setSelected(false);
            CK_Junior.setSelected(false);
        }
    }//GEN-LAST:event_CK_SuperActionPerformed

    private void CK_SeniorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CK_SeniorActionPerformed
          if(CK_Senior.isSelected()){
            CK_Super.setSelected(false);
            CK_Junior.setSelected(false);
        }
    }//GEN-LAST:event_CK_SeniorActionPerformed

    private void CK_JuniorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CK_JuniorActionPerformed
          if(CK_Junior.isSelected()){
            CK_Senior.setSelected(false);
            CK_Super.setSelected(false);
        }
    }//GEN-LAST:event_CK_JuniorActionPerformed
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CK_Junior;
    private javax.swing.JCheckBox CK_Senior;
    private javax.swing.JCheckBox CK_Super;
    public javax.swing.JTable ListeCommerciaux;
    private javax.swing.JPanel body;
    private javax.swing.JButton btnAjouterCommercial;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDeleteCommercial;
    private javax.swing.JButton btnEspaceCommerciaux;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnModifierCommercial;
    private javax.swing.JButton btnTelechargerFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panAjoutCommercial;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtPrenom;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables

    private Boolean validerData() {
        Boolean flag =true;
        try{ 
            Integer.parseInt(txtId.getText());   
        }catch(NumberFormatException e){
          flag = false; 
          JOptionPane.showMessageDialog(null, "Erreur de saisie sur ID", "Saisie des valeurs", JOptionPane.ERROR_MESSAGE);

        }
        if(txtNom.getText().isEmpty()){
            flag = false; 
            JOptionPane.showMessageDialog(null, "Nom Obligatoire", "Saisie des valeurs", JOptionPane.ERROR_MESSAGE);

        }
        if(txtPrenom.getText().isEmpty()){
            flag = false; 
            JOptionPane.showMessageDialog(null, "Prenom Obligatoire", "Saisie des valeurs", JOptionPane.ERROR_MESSAGE);
        }
        if(txtEmail.getText().isEmpty()){
            flag = false; 
            JOptionPane.showMessageDialog(null, "Email Obligatoire", "Saisie des valeurs", JOptionPane.ERROR_MESSAGE);
        }
        if(txtTel.getText().isEmpty()){
            flag = false; 
            JOptionPane.showMessageDialog(null, "Telephone Obligatoire", "Saisie des valeurs", JOptionPane.ERROR_MESSAGE);
        }
         if((CK_Junior.isSelected()== false)&&(CK_Senior.isSelected()==false)&&(CK_Super.isSelected()==false)){
            flag = false; 
            JOptionPane.showMessageDialog(null, "selectionner une categories", "Saisie des valeurs", JOptionPane.ERROR_MESSAGE);
        }
       
      
        
        return flag;
    }

    private void viderChamps() {
        txtId.setText("");
        txtNom.setText("");
        txtPrenom.setText("");
        txtEmail.setText("");
        txtTel.setText("");
        CK_Junior.setSelected(false);
        CK_Senior.setSelected(false);
        CK_Super.setSelected(false);
        
    }
}
